### ISSUE TITLE
[Bug] After rename app and delete it, app name stay in app list

### ISSUE THREAD

**Issue by volnes** [vackosar/search-based-launcher#42] opened 2016-10-07 05:42 UTC
Hi, found some bug install an app JumpGo, i rename it to different name and delete this app, but in app list this app name still here. When I try to run it nothing happens.

**Comment by vackosar** [comment] 2016-12-28 22:41
@volnes, I confirm. The cause it that does not catch uninstall event properly and does not remove app from extra and hidden app list. Manual fix for this is to use App List Selection from Menu and remove manually. Will fix this soon.

**Comment by vackosar** [comment] 2016-12-29 18:51
@volnes can you restest on v59?

**Comment by vackosar** [comment] 2016-12-30 18:11
Please reopen if this is still issue on v59.

**Closed by vackosar** 2016-12-30 18:11 UTC
